commit i386 static ruby

diff --git a/buildroot/opt/chef/bin/rdoc b/buildroot/opt/chef/bin/rdoc
--- a/buildroot/opt/chef/bin/rdoc
+++ b/buildroot/opt/chef/bin/rdoc
@@ -1,1 +1,10 @@
-/opt/chef/wrappers/ruby-1.9.2-p180/rdoc
+#!/usr/bin/env bash
+
+if [[ -s "/opt/chef/environments/ruby-1.9.2-p180" ]] ; then
+  source "/opt/chef/environments/ruby-1.9.2-p180"
+  exec rdoc "$@"
+else
+  echo "ERROR: Missing RVM environment file: '/opt/chef/environments/ruby-1.9.2-p180'" >&2
+  exit 1
+fi
+  
